In [37]:
import pandas as pd
import numpy as np

In [38]:
ads_index = pd.read_csv("./data/ads_data_index.csv")

In [39]:
ads_index

,count,groupMetadataID,start_time,end_time,nummsgs,filebase,folder,vehilceID,experimentID
0,1,3a116996-93a9-11ee-956e-9da2d070324c,1.674160e+18,1.674160e+18,1855470,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,13
1,2,2837eb9c-9542-11ee-956e-9da2d070324c,1.683310e+18,1.683320e+18,1149980,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,1
2,3,da853e0c-a10f-11ee-981c-d126ddbe9afa,1.684780e+18,1.684780e+18,459295,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,2
3,4,154fab12-a43f-11ee-88ec-eb6a8d5269b4,1.684780e+18,1.684780e+18,559423,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,3
4,7,ba6e1072-9524-11ee-956e-9da2d070324c,1.685540e+18,1.685540e+18,463801,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,4
...,...,...,...,...,...,...,...,...,...
325,199,f8fd0fd8-f243-11ee-bb3f-fb353e7798cd,1.701200e+18,1.701200e+18,758506,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701196779
326,200,58d78342-f24a-11ee-bb45-fb353e7798cd,1.701200e+18,1.701200e+18,727298,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701198151
327,201,25135418-f250-11ee-bb4a-fb353e7798cd,1.701200e+18,1.701200e+18,751183,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701199673
328,202,cbdc93f4-f255-11ee-bb4e-fb353e7798cd,1.701200e+18,1.701200e+18,705558,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,Van2,1701203037
329,203,de226278-f25a-11ee-bb4e-fb353e7798cd,1.701200e+18,1.701210e+18,743008,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,Van2,1701204159

## Cleaning and calculations

In [40]:
if "vehilceID" in ads_index.columns:
    ads_index.rename({'vehilceID': 'vehicleID'}, axis=1, inplace=True)


# ads_index['duration'] = ads_index['end_time'] - ads_index['start_time']

## Route Analysis

example split of a string to extract route color

In [41]:
s = '/Deployment_2_SEOhio/Blue Route/OU Pacifica/1674155613/20230119141333.record.00000'

s.split("/")[2]

'Blue Route'

In [42]:
routes = ads_index["filebase"].copy().apply(lambda s: s.split("/")[2])
ads_index["route"] = routes
ads_index

,count,groupMetadataID,start_time,end_time,nummsgs,filebase,folder,vehicleID,experimentID,route
0,1,3a116996-93a9-11ee-956e-9da2d070324c,1.674160e+18,1.674160e+18,1855470,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,13,Blue Route
1,2,2837eb9c-9542-11ee-956e-9da2d070324c,1.683310e+18,1.683320e+18,1149980,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,1,Blue Route
2,3,da853e0c-a10f-11ee-981c-d126ddbe9afa,1.684780e+18,1.684780e+18,459295,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,2,Blue Route
3,4,154fab12-a43f-11ee-88ec-eb6a8d5269b4,1.684780e+18,1.684780e+18,559423,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,3,Blue Route
4,7,ba6e1072-9524-11ee-956e-9da2d070324c,1.685540e+18,1.685540e+18,463801,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,4,Blue Route
...,...,...,...,...,...,...,...,...,...,...
325,199,f8fd0fd8-f243-11ee-bb3f-fb353e7798cd,1.701200e+18,1.701200e+18,758506,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701196779,GreenRoute
326,200,58d78342-f24a-11ee-bb45-fb353e7798cd,1.701200e+18,1.701200e+18,727298,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701198151,GreenRoute
327,201,25135418-f250-11ee-bb4a-fb353e7798cd,1.701200e+18,1.701200e+18,751183,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701199673,GreenRoute
328,202,cbdc93f4-f255-11ee-bb4e-fb353e7798cd,1.701200e+18,1.701200e+18,705558,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,Van2,1701203037,GreenRoute
329,203,de226278-f25a-11ee-bb4e-fb353e7798cd,1.701200e+18,1.701210e+18,743008,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,Van2,1701204159,GreenRoute

In [43]:
ads_index["route"].value_counts()

route
Blue Route    120
GreenRoute    109
RedRoute      101
Name: count, dtype: int64

## Vehicle Analysis

In [44]:
ads_index["vehicleID"].value_counts()

vehicleID
Van1          245
Van2           44
OUPacifica     41
Name: count, dtype: int64

In [45]:
d = pd.DataFrame(ads_index[["vehicleID", "route"]].value_counts(sort=False))
d['proportion'] = ads_index[["vehicleID", "route"]].value_counts(sort=False, normalize=True) * 100


d

                       count  proportion
vehicleID  route
OUPacifica Blue Route     20    6.060606
           GreenRoute     11    3.333333
           RedRoute       10    3.030303
Van1       Blue Route     84   25.454545
           GreenRoute     76   23.030303
           RedRoute       85   25.757576
Van2       Blue Route     16    4.848485
           GreenRoute     22    6.666667
           RedRoute        6    1.818182

In [46]:
e = pd.DataFrame(ads_index[["route", "vehicleID"]].value_counts(sort=False))

e['proportion'] = ads_index[["route", "vehicleID"]].value_counts(sort=False, normalize=True) * 100

e

                       count  proportion
route      vehicleID
Blue Route OUPacifica     20    6.060606
           Van1           84   25.454545
           Van2           16    4.848485
GreenRoute OUPacifica     11    3.333333
           Van1           76   23.030303
           Van2           22    6.666667
RedRoute   OUPacifica     10    3.030303
           Van1           85   25.757576
           Van2            6    1.818182

In [47]:
ads_index[ads_index['route'] == 'RedRoute'].sort_values(by='experimentID')

,count,groupMetadataID,start_time,end_time,nummsgs,filebase,folder,vehicleID,experimentID,route
5,11,1bbbfbae-c839-11ee-a7fc-dd032dba19e8,1.686170e+18,1.686170e+18,160256,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1686...,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1686...,OUPacifica,5,RedRoute
8,80,6d2ea45a-c839-11ee-a7fc-dd032dba19e8,1.694620e+18,1.694630e+18,1816742,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1694...,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1694...,OUPacifica,11,RedRoute
11,90,8fa6fe80-c869-11ee-a7fc-dd032dba19e8,1.695230e+18,1.695230e+18,2002226,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1695...,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1695...,OUPacifica,12,RedRoute
13,96,7fb7b9c0-c881-11ee-a7fc-dd032dba19e8,1.695840e+18,1.695840e+18,1892364,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1695...,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1695...,OUPacifica,15,RedRoute
17,109,51ef6da6-ca9f-11ee-909c-e1dc60cf66f9,1.696440e+18,1.696440e+18,1753843,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1696...,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1696...,OUPacifica,19,RedRoute
...,...,...,...,...,...,...,...,...,...,...
266,310,662741a4-f38a-11ee-bb4e-fb353e7798cd,1.707420e+18,1.707420e+18,1435965,/Deployment_2_SEOhio/RedRoute/TRCVan1/17074220...,/Deployment_2_SEOhio/RedRoute/TRCVan1/17074220...,Van1,1707422085,RedRoute
267,311,65cfbfd6-f396-11ee-bb4e-fb353e7798cd,1.708010e+18,1.708010e+18,1638330,/Deployment_2_SEOhio/RedRoute/TRCVan1/17080115...,/Deployment_2_SEOhio/RedRoute/TRCVan1/17080115...,Van1,1708011504,RedRoute
268,312,c25271be-f3a4-11ee-bb4e-fb353e7798cd,1.708020e+18,1.708020e+18,1692068,/Deployment_2_SEOhio/RedRoute/TRCVan1/17080151...,/Deployment_2_SEOhio/RedRoute/TRCVan1/17080151...,Van1,1708015127,RedRoute
269,313,868de15e-f3b3-11ee-bb4e-fb353e7798cd,1.708030e+18,1.708030e+18,1691034,/Deployment_2_SEOhio/RedRoute/TRCVan1/17080246...,/Deployment_2_SEOhio/RedRoute/TRCVan1/17080246...,Van1,1708024622,RedRoute
281,325,3344a3c0-f502-11ee-8afa-cb629b0d53e6,1.708630e+18,1.708630e+18,1633989,/Deployment_2_SEOhio/RedRoute/TRCVan1/17086256...,/Deployment_2_SEOhio/RedRoute/TRCVan1/17086256...,Van1,1708625632,RedRoute

In [48]:
import os


red_IDs = ads_index[ads_index['route'] == 'RedRoute']['groupMetadataID'].tolist()

ids = []

red_IDs

for id in red_IDs:
    if f'{id}.csv' in os.listdir('./data/chassis'):
        ids.append(id)

ids

['1bbbfbae-c839-11ee-a7fc-dd032dba19e8',
 '6d2ea45a-c839-11ee-a7fc-dd032dba19e8',
 '8fa6fe80-c869-11ee-a7fc-dd032dba19e8',
 '7fb7b9c0-c881-11ee-a7fc-dd032dba19e8',
 '51ef6da6-ca9f-11ee-909c-e1dc60cf66f9',
 '8437f77a-cab7-11ee-909c-e1dc60cf66f9',
 '853ef120-cad3-11ee-909c-e1dc60cf66f9',
 'd12cd1c4-caec-11ee-909c-e1dc60cf66f9',
 'c338788a-d324-11ee-b437-336917683bb8',
 'c9c6856c-d33c-11ee-b437-336917683bb8']

## Choosing a Red Route gmID

In [49]:
gmID = "1bbbfbae-c839-11ee-a7fc-dd032dba19e8"

df_chassis = pd.read_csv(f'./data/chassis/{gmID}.csv')
df_pose = pd.read_csv(f'./data/best_pose/{gmID}.csv')
df_metadata = pd.read_csv(f'./data/metadata/{gmID}.csv')
index_data = ads_index[ads_index['groupMetadataID'] == gmID].copy()

df_chassis.sort_values(by='time', inplace=True)
df_pose.sort_values(by='time', inplace=True)

In [50]:
df_chassis.head()

,yawRate,drivingMode,topic,msgsize,time,gearLocation,metadataID,throttlePercentage,steeringPercentage,brakePercentage,...,header.sequenceNum,header.timestampSec,wheelSpeed.isWheelSpdRrValid,wheelSpeed.wheelSpdRr,wheelSpeed.isWheelSpdRlValid,wheelSpeed.wheelSpdFr,wheelSpeed.isWheelSpdFrValid,wheelSpeed.wheelSpdRl,wheelSpeed.wheelSpdFl,wheelSpeed.isWheelSpdFlValid
259,0,COMPLETE_AUTO_DRIVE,/apollo/canbus/chassis,134,1686166863105735847,GEAR_DRIVE,4a233e38-c840-11ee-a7fc-dd032dba19e8,33.6,0.314975,0.0,...,73216,1.686167e+09,True,64.402679,True,64.612114,True,64.350319,64.559753,True
7720,0,COMPLETE_AUTO_DRIVE,/apollo/canbus/chassis,134,1686166863131527027,GEAR_DRIVE,4a233e38-c840-11ee-a7fc-dd032dba19e8,33.6,0.314975,0.0,...,73217,1.686167e+09,True,64.402679,True,64.612114,True,64.350319,64.559753,True
5836,0,COMPLETE_AUTO_DRIVE,/apollo/canbus/chassis,134,1686166863145677935,GEAR_DRIVE,4a233e38-c840-11ee-a7fc-dd032dba19e8,33.6,0.314975,0.0,...,73218,1.686167e+09,True,64.402679,True,64.612114,True,64.350319,64.559753,True
8008,0,COMPLETE_AUTO_DRIVE,/apollo/canbus/chassis,134,1686166863165670800,GEAR_DRIVE,4a233e38-c840-11ee-a7fc-dd032dba19e8,34.0,0.314975,0.0,...,73219,1.686167e+09,True,64.507401,True,64.664474,True,64.507401,64.664474,True
7300,0,COMPLETE_AUTO_DRIVE,/apollo/canbus/chassis,134,1686166863187109453,GEAR_DRIVE,4a233e38-c840-11ee-a7fc-dd032dba19e8,34.0,0.314975,0.0,...,73220,1.686167e+09,True,64.507401,True,64.664474,True,64.507401,64.664474,True

In [51]:
df_pose.head()

,time,longitudeStdDev,numSatsMulti,groupMetadataID,numSatsTracked,latitudeStdDev,differentialAge,longitude,solType,solutionAge,solStatus,latitude,numSatsInSolution
107,1686166864077051217,0.017091,11,1bbbfbae-c839-11ee-a7fc-dd032dba19e8,14,0.015546,2.0,-82.085071,NARROW_INT,0.0,SOL_COMPUTED,39.349754,11
158,1686166865043760126,0.016349,11,1bbbfbae-c839-11ee-a7fc-dd032dba19e8,15,0.015254,2.0,-82.085274,NARROW_INT,0.0,SOL_COMPUTED,39.349905,13
159,1686166866037369591,0.014225,11,1bbbfbae-c839-11ee-a7fc-dd032dba19e8,15,0.013347,1.0,-82.085487,NARROW_INT,0.0,SOL_COMPUTED,39.350054,14
22,1686166867037099412,0.014443,11,1bbbfbae-c839-11ee-a7fc-dd032dba19e8,15,0.013326,1.0,-82.085706,NARROW_INT,0.0,SOL_COMPUTED,39.350203,14
76,1686166868042745516,0.014586,11,1bbbfbae-c839-11ee-a7fc-dd032dba19e8,15,0.013400,1.0,-82.085928,NARROW_INT,0.0,SOL_COMPUTED,39.350349,13

In [52]:
df_metadata.head()

,_id,groupMetadataID,time,driver,experimentID,other.Map,other.Notes,other.Weather
0,43773e83-c842-11ee-a7fc-dd032dba19e8,1bbbfbae-c839-11ee-a7fc-dd032dba19e8,1686167016856576519,1,5,ohio_athens_red_v2,33 to 550 - almost end of 550. 2x manual takeo...,"75F, dry"

In [53]:
index_data

,count,groupMetadataID,start_time,end_time,nummsgs,filebase,folder,vehicleID,experimentID,route
5,11,1bbbfbae-c839-11ee-a7fc-dd032dba19e8,1.686170e+18,1.686170e+18,160256,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1686...,/Deployment_2_SEOhio/RedRoute/OU Pacifica/1686...,OUPacifica,5,RedRoute