# testing_ads_index

In [174]:
import pandas as pd
import numpy as np

In [175]:
ads_index = pd.read_csv("./data/ads_data_index.csv")

In [176]:
ads_index

,count,groupMetadataID,start_time,end_time,nummsgs,filebase,folder,vehilceID,experimentID
0,1,3a116996-93a9-11ee-956e-9da2d070324c,1.674160e+18,1.674160e+18,1855470,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,13
1,2,2837eb9c-9542-11ee-956e-9da2d070324c,1.683310e+18,1.683320e+18,1149980,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,1
2,3,da853e0c-a10f-11ee-981c-d126ddbe9afa,1.684780e+18,1.684780e+18,459295,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,2
3,4,154fab12-a43f-11ee-88ec-eb6a8d5269b4,1.684780e+18,1.684780e+18,559423,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,3
4,7,ba6e1072-9524-11ee-956e-9da2d070324c,1.685540e+18,1.685540e+18,463801,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,4
...,...,...,...,...,...,...,...,...,...
325,199,f8fd0fd8-f243-11ee-bb3f-fb353e7798cd,1.701200e+18,1.701200e+18,758506,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701196779
326,200,58d78342-f24a-11ee-bb45-fb353e7798cd,1.701200e+18,1.701200e+18,727298,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701198151
327,201,25135418-f250-11ee-bb4a-fb353e7798cd,1.701200e+18,1.701200e+18,751183,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701199673
328,202,cbdc93f4-f255-11ee-bb4e-fb353e7798cd,1.701200e+18,1.701200e+18,705558,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,Van2,1701203037
329,203,de226278-f25a-11ee-bb4e-fb353e7798cd,1.701200e+18,1.701210e+18,743008,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,Van2,1701204159

## Cleaning and calculations

In [177]:
if "vehilceID" in ads_index.columns:
    ads_index.rename({'vehilceID': 'vehicleID'}, axis=1, inplace=True)


# ads_index['duration'] = ads_index['end_time'] - ads_index['start_time']

example split of a string to extract route color

In [178]:
s = '/Deployment_2_SEOhio/Blue Route/OU Pacifica/1674155613/20230119141333.record.00000'

s.split("/")[2]

'Blue Route'

In [179]:
routes = ads_index["filebase"].copy().apply(lambda s: s.split("/")[2])
ads_index["route"] = routes
ads_index

,count,groupMetadataID,start_time,end_time,nummsgs,filebase,folder,vehicleID,experimentID,route
0,1,3a116996-93a9-11ee-956e-9da2d070324c,1.674160e+18,1.674160e+18,1855470,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,13,Blue Route
1,2,2837eb9c-9542-11ee-956e-9da2d070324c,1.683310e+18,1.683320e+18,1149980,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,1,Blue Route
2,3,da853e0c-a10f-11ee-981c-d126ddbe9afa,1.684780e+18,1.684780e+18,459295,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,2,Blue Route
3,4,154fab12-a43f-11ee-88ec-eb6a8d5269b4,1.684780e+18,1.684780e+18,559423,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,3,Blue Route
4,7,ba6e1072-9524-11ee-956e-9da2d070324c,1.685540e+18,1.685540e+18,463801,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,/Deployment_2_SEOhio/Blue Route/OU Pacifica/16...,OUPacifica,4,Blue Route
...,...,...,...,...,...,...,...,...,...,...
325,199,f8fd0fd8-f243-11ee-bb3f-fb353e7798cd,1.701200e+18,1.701200e+18,758506,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701196779,GreenRoute
326,200,58d78342-f24a-11ee-bb45-fb353e7798cd,1.701200e+18,1.701200e+18,727298,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701198151,GreenRoute
327,201,25135418-f250-11ee-bb4a-fb353e7798cd,1.701200e+18,1.701200e+18,751183,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170119...,Van2,1701199673,GreenRoute
328,202,cbdc93f4-f255-11ee-bb4e-fb353e7798cd,1.701200e+18,1.701200e+18,705558,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,Van2,1701203037,GreenRoute
329,203,de226278-f25a-11ee-bb4e-fb353e7798cd,1.701200e+18,1.701210e+18,743008,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,/Deployment_2_SEOhio/GreenRoute/TRCVan2/170120...,Van2,1701204159,GreenRoute

## Route Analysis

In [180]:
ads_index["route"].value_counts()

route
Blue Route    120
GreenRoute    109
RedRoute      101
Name: count, dtype: int64

## Vehicle Analysis

In [181]:
ads_index["vehicleID"].value_counts()

vehicleID
Van1          245
Van2           44
OUPacifica     41
Name: count, dtype: int64

In [182]:
d = pd.DataFrame(ads_index[["vehicleID", "route"]].value_counts(sort=False))
d['proportion'] = ads_index[["vehicleID", "route"]].value_counts(sort=False, normalize=True)


d

                       count  proportion
vehicleID  route
OUPacifica Blue Route     20    0.060606
           GreenRoute     11    0.033333
           RedRoute       10    0.030303
Van1       Blue Route     84    0.254545
           GreenRoute     76    0.230303
           RedRoute       85    0.257576
Van2       Blue Route     16    0.048485
           GreenRoute     22    0.066667
           RedRoute        6    0.018182

In [183]:
e = pd.DataFrame(ads_index[["route", "vehicleID"]].value_counts(sort=False))

e['proportion'] = ads_index[["route", "vehicleID"]].value_counts(sort=False, normalize=True) * 100

e

                       count  proportion
route      vehicleID
Blue Route OUPacifica     20    6.060606
           Van1           84   25.454545
           Van2           16    4.848485
GreenRoute OUPacifica     11    3.333333
           Van1           76   23.030303
           Van2           22    6.666667
RedRoute   OUPacifica     10    3.030303
           Van1           85   25.757576
           Van2            6    1.818182